apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: imagePolicy
metadata:
  name: vacancy-parser
  namespace: flux-system
spec:
  ImageRepositoryRef:
    name: vacancy-parser
  policy:
    semver:
      range: '>=0.0.1'