apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vacancy-parser
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/mark-grigorev/vacancy-parser
  ref:
    branch: master
  secretRef:
    name: vacancy-parser-github