apiVersion: apps/v1
kind: Deployment
metadata:
  name: fingo
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fingo
  template:
    metadata:
      labels:
        app: fingo
    spec:
      containers:
        - name: nginx
          image: ghcr.io/mark-grigorev/fingo:latest
          ports:
            - containerPort: 80
          resources:
            requests: 
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 20m
              memory: 64Mi
