apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "84.5.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: false
    
    alertmanager:
      enabled: false

    prometheus:
      service: 
        type: NodePort
        nodePort: 30900
      prometheusSpec:
        retention: 4d
    prometheus-node-exporter:
      extraArgs:
        - --collector.systemd
        - --collector.systemd.unit-include=postgresql@17-main.service
        - --collector.textfile.directory=/host/textfile_collector
      extraHostVolumeMounts:
        - name: textfile-collector
          hostPath: /var/lib/node_exporter/textfile_collector
          mountPath: /host/textfile_collector
          readOnly: true
        - name: dbus
          hostPath: /run/dbus/system_bus_socket
          mountPath: /run/dbus/system_bus_socket
          readOnly: false
