apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}
            {{- if .Values.vault.enabled }}
            annotations:
                vault.hashicorp.com/agent-inject: "true"
                vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
                vault.hashicorp.com/agent-inject-secret-config: {{ printf "secret/data/%s" .Release.Name | quote }}
                vault.hashicorp.com/agent-inject-template-config: |
{{ .Values.vault.template | trim | nindent 20 }}
            {{- end }}
        spec:
            {{- if .Values.serviceAccount.create }}
            serviceAccountName: {{ .Release.Name }}
            {{- end }}
            containers:
              {{- if .Values.nginx.enabled }}
              - name: nginx
                image: {{ .Values.nginx.image }}
                ports:
                  - containerPort: 80
                resources: {{- toYaml .Values.nginx.resources | nindent 18 }}
              {{- end }}
              - name: {{ .Release.Name }}
                image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
                {{- if .Values.command }}
                command: {{- toYaml .Values.command | nindent 18 }}
                {{- end }}
                {{- if .Values.env }}
                env: {{- toYaml .Values.env | nindent 18 }}
                {{- end }}
                ports:
                  - containerPort: {{ .Values.containerPort }}
                resources: {{- toYaml .Values.resources | nindent 18 }}
