apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mark-alldevops
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mark-alldevops
  policy:
    semver:
      range: '>=0.0.1'